name: communihelp_app
description: "Flutter capstone project in software engineering."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3

  image_picker: ^0.8.6
  flutter_slidable: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/dashboard/
    - assets/images/infographics/
    - assets/images/infographics/button_images/
    - assets/images/bottom_app_bar/
    - assets/images/logo/
    - assets/images/background/
    - assets/images/

      # fonts:
  #   - family: Still searching for fonts
  #     fonts:
  #     - asset: fonts/Porsche-Regular.ttf //example font
