name: communihelp_app
description: "Flutter capstone project in software engineering."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #utilities
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  image_picker: ^1.0.0
  image_cropper: ^8.0.2
  flutter_slidable: ^3.1.0
  flutter_keyboard_visibility: ^6.0.0
  logger: ^2.4.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  flutter_carousel_widget: ^3.1.0
  flutter_exit_app: ^1.1.4 #for exitting the app
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http: ^1.2.2
  flutter_dotenv: ^5.2.1 #storing api keys

  #Firebase and firestore
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3

  

  #Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #maps
  flutter_map: ^7.0.2
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

  #Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - lib/.env
    
    - assets/images/dashboard/
    - assets/images/dashboard/checklist_images/
    - assets/images/bottom_app_bar/
    - assets/images/logo/
    - assets/images/background/
    - assets/images/
    - assets/images/weather/

    #inforgrpahics assets
    - assets/images/infographics/
    - assets/images/infographics/button_images/
    - assets/images/infographics/natural_infographics/

      # fonts:
  #   - family: Still searching for fonts
  #     fonts:
  #     - asset: fonts/Porsche-Regular.ttf //example font
