name: communihelp_app
description: "Flutter capstone project in software engineering."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0

  get: ^4.6.6
  image_picker: ^1.0.0
  flutter_slidable: ^3.1.0

  #Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

  #Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/dashboard/
    - assets/images/dashboard/checklist_images/
    - assets/images/infographics/
    - assets/images/infographics/button_images/
    - assets/images/bottom_app_bar/
    - assets/images/logo/
    - assets/images/background/
    - assets/images/

      # fonts:
  #   - family: Still searching for fonts
  #     fonts:
  #     - asset: fonts/Porsche-Regular.ttf //example font
