name: communihelp_app
description: "Flutter capstone project in software engineering."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #utilities
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.0
  image_cropper: ^8.0.2
  flutter_slidable: ^3.1.0
  flutter_keyboard_visibility: ^6.0.0
  logger: ^2.4.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  flutter_carousel_widget: ^3.1.0
  flutter_exit_app: ^1.1.4 #for exitting the app
  path_provider: ^2.1.5
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http: ^1.2.2
  flutter_dotenv: ^5.2.1 #storing api keys
  flutter_local_notifications: ^18.0.0
  flutter_native_splash: ^2.4.2
  html: ^0.15.5

  #icon
  

  #Firebase and firestore
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3

  

  #Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #maps
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: 'assets/images/logo/logo_communihelp.jpg'
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo/logo_communihelp.jpg"

  #Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.13




flutter:
  uses-material-design: true

  assets:
    - lib/.env
    
    - assets/images/dashboard/
    - assets/images/dashboard/checklist_images/
    - assets/images/bottom_app_bar/
    - assets/images/logo/
    - assets/images/background/
    - assets/images/
    - assets/images/weather/

    

    #inforgrpahics assets
    - assets/images/infographics/
    - assets/images/infographics/button_images/
    - assets/images/infographics/natural_infographics/typhoon/typhoon_En/
    - assets/images/infographics/natural_infographics/typhoon/typhoon_Fil/
    - assets/images/infographics/natural_infographics/typhoon/typhoon_Akl/
    - assets/images/infographics/natural_infographics/flood/flood_En/
    - assets/images/infographics/natural_infographics/flood/flood_Fil/
    - assets/images/infographics/natural_infographics/flood/flood_Akl/
    - assets/images/infographics/natural_infographics/landslide/landslide_En/
    - assets/images/infographics/natural_infographics/landslide/landslide_Fil/
    - assets/images/infographics/natural_infographics/landslide/landslide_Akl/
    - assets/images/infographics/natural_infographics/earthquake/earthquake_En/
    - assets/images/infographics/natural_infographics/earthquake/earthquake_Fil/
    - assets/images/infographics/natural_infographics/earthquake/earthquake_Akl/
    
    - assets/images/infographics/manmade_infographics/burn/burn_En/
    - assets/images/infographics/manmade_infographics/burn/burn_Fil/
    - assets/images/infographics/manmade_infographics/burn/burn_Akl/
    - assets/images/infographics/manmade_infographics/pollution/pollution_En/
    - assets/images/infographics/manmade_infographics/pollution/pollution_Fil/
    - assets/images/infographics/manmade_infographics/pollution/pollution_Akl/
    - assets/images/infographics/manmade_infographics/structural/structural_En/
    - assets/images/infographics/manmade_infographics/structural/structural_Fil/
    - assets/images/infographics/manmade_infographics/structural/structural_Akl/
    - assets/images/infographics/manmade_infographics/vehicular/vehicular_En/
    - assets/images/infographics/manmade_infographics/vehicular/vehicular_Fil/
    - assets/images/infographics/manmade_infographics/vehicular/vehicular_Akl/
    

      # fonts:
  #   - family: Still searching for fonts
  #     fonts:
  #     - asset: fonts/Porsche-Regular.ttf //example font
    
